# Generated by Django 3.0.6 on 2020-05-21 20:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSneakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sneakers', max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneakers_name', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='WayToUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SneakersInstance',
            fields=[
                ('color', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('size', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Sneakers_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.Sneakers')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.ImageSneakers')),
            ],
        ),
        migrations.AddField(
            model_name='sneakers',
            name='way_to_use',
            field=models.ManyToManyField(to='Shop.WayToUse'),
        ),
    ]
