# Generated by Django 3.0.6 on 2020-05-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakersinstance',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
