# Generated by Django 3.0.6 on 2020-05-21 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20200521_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakersinstance',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.ImageSneakers'),
        ),
    ]
