# Generated by Django 3.0.6 on 2020-05-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20200521_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakersinstance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
