# Generated by Django 3.0.6 on 2020-05-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_shopuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
